
abby = User.create(
	first_name: "Abby", 
	last_name: "Miller", 
	is_admin: false, 
	telephone: nil, 
	email: "abby@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/abigezunt", 
	html_url: "https://github.com/abigezunt", 
	repos_url: "https://api.github.com/users/abigezunt/repos", 
	gists_url: "https://api.github.com/users/abigezunt/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "abigezunt", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/abigezunt/followers", 
	following_url: "https://api.github.com/users/abigezunt/following{/other_user}", 
	starred_url: "https://api.github.com/users/abigezunt/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/abigezunt/subscriptions", 
	organizations_url: "https://api.github.com/users/abigezunt/orgs", 
	events_url: "https://api.github.com/users/abigezunt/events{/privacy}", 
	received_events_url: "https://api.github.com/users/abigezunt/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

dan = User.create(
	first_name: "Dan", 
	last_name: "Crews", 
	is_admin: false, 
	telephone: nil, 
	email: "dan@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/MicFin", 
	html_url: "https://github.com/MicFin", 
	repos_url: "https://api.github.com/users/MicFin/repos", 
	gists_url: "https://api.github.com/users/MicFin/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "MicFin", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/MicFin/followers", 
	following_url: "https://api.github.com/users/MicFin/following{/other_user}", 
	starred_url: "https://api.github.com/users/MicFin/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/MicFin/subscriptions", 
	organizations_url: "https://api.github.com/users/MicFin/orgs", 
	events_url: "https://api.github.com/users/MicFin/events{/privacy}", 
	received_events_url: "https://api.github.com/users/MicFin/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

	mike = User.create(
	first_name: "Mike", 
	last_name: "Finn", 
	is_admin: false, 
	telephone: nil, 
	email: "mike@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/MicFin", 
	html_url: "https://github.com/MicFin", 
	repos_url: "https://api.github.com/users/MicFin/repos", 
	gists_url: "https://api.github.com/users/MicFin/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "MicFin", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/MicFin/followers", 
	following_url: "https://api.github.com/users/MicFin/following{/other_user}", 
	starred_url: "https://api.github.com/users/MicFin/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/MicFin/subscriptions", 
	organizations_url: "https://api.github.com/users/MicFin/orgs", 
	events_url: "https://api.github.com/users/MicFin/events{/privacy}", 
	received_events_url: "https://api.github.com/users/MicFin/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

	rahul = User.create(
	first_name: "Rahul", 
	last_name: "Hore", 
	is_admin: false, 
	telephone: nil, 
	email: "rahul@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/O-I", 
	html_url: "https://github.com/O-I", 
	repos_url: "https://api.github.com/users/O-I/repos", 
	gists_url: "https://api.github.com/users/O-I/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "O-I", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/O-I/followers", 
	following_url: "https://api.github.com/users/O-I/following{/other_user}", 
	starred_url: "https://api.github.com/users/O-I/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/O-I/subscriptions", 
	organizations_url: "https://api.github.com/users/O-I/orgs", 
	events_url: "https://api.github.com/users/O-I/events{/privacy}", 
	received_events_url: "https://api.github.com/users/O-I/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

emma = User.create(
	first_name: "Emma", 
	last_name: "Spencer", 
	is_admin: false, 
	telephone: nil, 
	email: "emma@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/enspencer", 
	html_url: "https://github.com/enspencer", 
	repos_url: "https://api.github.com/users/enspencer/repos", 
	gists_url: "https://api.github.com/users/enspencer/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "enspencer", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/enspencer/followers", 
	following_url: "https://api.github.com/users/enspencer/following{/other_user}", 
	starred_url: "https://api.github.com/users/enspencer/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/enspencer/subscriptions", 
	organizations_url: "https://api.github.com/users/enspencer/orgs", 
	events_url: "https://api.github.com/users/enspencer/events{/privacy}", 
	received_events_url: "https://api.github.com/users/enspencer/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

bryce = User.create(
	first_name: "Bryce", 
	last_name: "Lambert", 
	is_admin: false, 
	telephone: nil, 
	email: "bryce@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/brycelambert", 
	html_url: "https://github.com/brycelambert", 
	repos_url: "https://api.github.com/users/brycelambert/repos", 
	gists_url: "https://api.github.com/users/brycelambert/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "brycelambert", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/brycelambert/followers", 
	following_url: "https://api.github.com/users/brycelambert/following{/other_user}", 
	starred_url: "https://api.github.com/users/brycelambert/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/brycelambert/subscriptions", 
	organizations_url: "https://api.github.com/users/brycelambert/orgs", 
	events_url: "https://api.github.com/users/brycelambert/events{/privacy}", 
	received_events_url: "https://api.github.com/users/brycelambert/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

blake = User.create(
	first_name: "Blake", 
	last_name: "Ruddock", 
	is_admin: false, 
	telephone: nil, 
	email: "blake@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/blakeruddock", 
	html_url: "https://github.com/blakeruddock", 
	repos_url: "https://api.github.com/users/blakeruddock/repos", 
	gists_url: "https://api.github.com/users/blakeruddock/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "blakeruddock", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/blakeruddock/followers", 
	following_url: "https://api.github.com/users/blakeruddock/following{/other_user}", 
	starred_url: "https://api.github.com/users/blakeruddock/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/blakeruddock/subscriptions", 
	organizations_url: "https://api.github.com/users/blakeruddock/orgs", 
	events_url: "https://api.github.com/users/blakeruddock/events{/privacy}", 
	received_events_url: "https://api.github.com/users/blakeruddock/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

ben = User.create(
	first_name: "Ben", 
	last_name: "Winter", 
	is_admin: false, 
	telephone: nil, 
	email: "ben@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/bengwinter", 
	html_url: "https://github.com/bengwinter", 
	repos_url: "https://api.github.com/users/bengwinter/repos", 
	gists_url: "https://api.github.com/users/bengwinter/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "bengwinter", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/bengwinter/followers", 
	following_url: "https://api.github.com/users/bengwinter/following{/other_user}", 
	starred_url: "https://api.github.com/users/bengwinter/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/bengwinter/subscriptions", 
	organizations_url: "https://api.github.com/users/bengwinter/orgs", 
	events_url: "https://api.github.com/users/bengwinter/events{/privacy}", 
	received_events_url: "https://api.github.com/users/bengwinter/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")


amal = User.create(
	first_name: "Amal", 
	last_name: "Hussein", 
	is_admin: false, 
	telephone: nil, 
	email: "amal@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/amalhussein", 
	html_url: "https://github.com/amalhussein", 
	repos_url: "https://api.github.com/users/amalhussein/repos", 
	gists_url: "https://api.github.com/users/amalhussein/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "amalhussein", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/amalhussein/followers", 
	following_url: "https://api.github.com/users/amalhussein/following{/other_user}", 
	starred_url: "https://api.github.com/users/amalhussein/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/amalhussein/subscriptions", 
	organizations_url: "https://api.github.com/users/amalhussein/orgs", 
	events_url: "https://api.github.com/users/amalhussein/events{/privacy}", 
	received_events_url: "https://api.github.com/users/amalhussein/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")


matt = User.create(
	first_name: "Matt", 
	last_name: "Clement", 
	is_admin: false, 
	telephone: nil, 
	email: "matt@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/darkmoves", 
	html_url: "https://github.com/darkmoves", 
	repos_url: "https://api.github.com/users/darkmoves/repos", 
	gists_url: "https://api.github.com/users/darkmoves/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "darkmoves", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/darkmoves/followers", 
	following_url: "https://api.github.com/users/darkmoves/following{/other_user}", 
	starred_url: "https://api.github.com/users/darkmoves/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/darkmoves/subscriptions", 
	organizations_url: "https://api.github.com/users/darkmoves/orgs", 
	events_url: "https://api.github.com/users/darkmoves/events{/privacy}", 
	received_events_url: "https://api.github.com/users/darkmoves/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

teddy = User.create(
	first_name: "Teddy", 
	last_name: "Cleveland", 
	is_admin: false, 
	telephone: nil, 
	email: "teddy@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/tcclevela", 
	html_url: "https://github.com/tcclevela", 
	repos_url: "https://api.github.com/users/tcclevela/repos", 
	gists_url: "https://api.github.com/users/tcclevela/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "tcclevela", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/tcclevela/followers", 
	following_url: "https://api.github.com/users/tcclevela/following{/other_user}", 
	starred_url: "https://api.github.com/users/tcclevela/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/tcclevela/subscriptions", 
	organizations_url: "https://api.github.com/users/tcclevela/orgs", 
	events_url: "https://api.github.com/users/tcclevela/events{/privacy}", 
	received_events_url: "https://api.github.com/users/tcclevela/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")

david = User.create(
	first_name: "David", 
	last_name: "Fisher", 
	is_admin: false, 
	telephone: nil, 
	email: "david@example.com",
	password: "secretness" ,
	street_address: nil, 
	city: nil, 
	state: nil, 
	zip_code: nil, 
	emergency_contact: nil, 
	emergency_contact_phone: nil, 
	github_url: "https://api.github.com/users/tibbon", 
	html_url: "https://github.com/tibbon", 
	repos_url: "https://api.github.com/users/tibbon/repos", 
	gists_url: "https://api.github.com/users/tibbon/gists{/gist_id}", 
	avatar_url: "https://0.gravatar.com/avatar/afb9c4e3401a6e54d045299f25cfbecf?d=https%3A%2F%2Fidenticons.github.com%2F5c284cd1782086a873770ab06d629e36.png&r=x", 
	public_repos: 88, 
	followers: 14, 
	following: 17, 
	github_id: 5377229, 
	github_login: "tibbon", 
	gravatar_id: 0, 
	followers_url: "https://api.github.com/users/tibbon/followers", 
	following_url: "https://api.github.com/users/tibbon/following{/other_user}", 
	starred_url: "https://api.github.com/users/tibbon/starred{/owner}{/repo}", 
	subscriptions_url: "https://api.github.com/users/tibbon/subscriptions", 
	organizations_url: "https://api.github.com/users/tibbon/orgs", 
	events_url: "https://api.github.com/users/tibbon/events{/privacy}", 
	received_events_url: "https://api.github.com/users/tibbon/received_events", 
	type: "User", 
	site_admin: "f", 
	public_gists: "0", 
	created_github_profile: "2013-09-03 23:06:57", 
	last_updated_github_at: "2013-11-21 21:07:38", 
	biography: "Words words words")


boston_wdi = Course.create(name: "WDI", location: "Boston", session: 'Fall 2013', start_date: Date.today - 1.months, end_date: Date.today + 2.months)
CourseMembership.create(user: abby, course: boston_wdi, role: 'student')
CourseMembership.create(user: amal, course: boston_wdi, role: 'student')
CourseMembership.create(user: matt, course: boston_wdi, role: 'student')

nyc_wdi_summer = Course.create(name: "OLD_WDI", location: "NYC", session: 'Summer 2013', start_date: Date.today - 6.months, end_date: Date.today - 3.months)
CourseMembership.create(user: teddy, course: nyc_wdi_summer, role: 'student')

CourseMembership.create(user: david, course: boston_wdi, role: 'teacher')
CourseMembership.create(user: teddy, course: boston_wdi, role: 'teacher')

first_assignment = Assignment.create(
	course: boston_wdi,
	title: "Whatever",
	description: "More words",
	github_login: "tibbon",
	github_repo: "tibbon/ga-string-analysis-homework",
	due_date: Date.today,
	assignment_type: "homework"
)

OneOnOne.create(
	student_id: abby.id,
	teacher_id: david.id,
	course: boston_wdi,
	date: Date.today,
	notes: "words words words this student is kinda awesome"
)
